# Generated by Django 4.2.7 on 2024-01-04 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('journalist_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=256)),
                ('photo', models.ImageField(default='', upload_to='images/profile_pictures')),
                ('is_chief', models.BooleanField()),
                ('slug', models.SlugField(allow_unicode=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalistPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalists', to='news_service.journalist')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='images/news_pictures')),
                ('content', models.TextField()),
                ('content_html', models.TextField(editable=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('approve', models.BooleanField()),
                ('author', models.ManyToManyField(through='news_service.JournalistPost', to='news_service.journalist')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='news_service.theme')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddField(
            model_name='journalistpost',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news_service.post'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='posts',
            field=models.ManyToManyField(through='news_service.JournalistPost', to='news_service.post'),
        ),
        migrations.AddField(
            model_name='journalist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journalist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='journalistpost',
            unique_together={('posts', 'journalist')},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_html', models.TextField(editable=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('approve', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='news_service.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
                'unique_together': {('user', 'content')},
            },
        ),
    ]
