# Generated by Django 4.2.7 on 2024-01-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0002_bulletin_suscriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin_suscriptor',
            name='is_suscript',
        ),
        migrations.RemoveField(
            model_name='bulletin_suscriptor',
            name='user',
        ),
        migrations.AddField(
            model_name='bulletin_suscriptor',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletin_suscriptor',
            name='username',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
