# Generated by Django 4.2.7 on 2024-01-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0003_remove_bulletin_suscriptor_is_suscript_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalistpost',
            old_name='posts',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='journalistpost',
            unique_together={('post', 'journalist')},
        ),
    ]
