# Generated by Django 4.2.7 on 2024-01-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0004_rename_posts_journalistpost_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalistpost',
            old_name='post',
            new_name='posts',
        ),
        migrations.AlterUniqueTogether(
            name='journalistpost',
            unique_together={('posts', 'journalist')},
        ),
    ]
