# Generated by Django 4.2.7 on 2024-01-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_service', '0005_rename_post_journalistpost_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalist',
            name='journalist_id',
        ),
        migrations.AlterField(
            model_name='journalist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='journalist', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
