# Generated by Django 4.2.7 on 2024-02-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0007_rename_author_post_other_authors_post_main_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='other_authors',
            field=models.ManyToManyField(blank=True, through='news_service.JournalistPost', to='news_service.journalist'),
        ),
    ]
