# Generated by Django 4.2.7 on 2024-02-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0008_alter_post_other_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalist',
            name='is_chief',
        ),
    ]
