# Generated by Django 4.2.7 on 2024-02-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0009_remove_journalist_is_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
