# Generated by Django 4.2.7 on 2024-02-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0011_alter_journalist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalist',
            name='email',
        ),
    ]
