# Generated by Django 4.2.7 on 2024-02-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0013_alter_post_other_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='other_authors',
            field=models.ManyToManyField(blank=True, through='news_service.JournalistPost', to='news_service.journalist'),
        ),
    ]
