# Generated by Django 4.2.7 on 2024-02-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0016_alter_post_other_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
