# Generated by Django 4.2.7 on 2024-03-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news_service', '0017_alter_post_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bulletin_suscriptor', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Bulletin_Suscriptor',
        ),
    ]
