# Generated by Django 4.2.7 on 2024-03-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0018_client_delete_bulletin_suscriptor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='author', to='news_service.client'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'content')},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
